name: 'Azure Key Vault Explorer'
description: 'Get secret and secret value from Azure Key Vault'
inputs:
  keyvault:  # id of input
    description: 'Name of keyvault'
    required: true
  secret:
    description: "Name of key vault secret"
    required: true
outputs:
  secret: # output will be available to future steps
    description: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
